# Source: jxboot-helmfile-resources/templates/ingress-config-configmap.yaml
apiVersion: v1
data:
  domain: "permanent.idmocp.lab.eng.rdu2.redhat.com"
  email: ""
  exposer: "Ingress"
  issuer: ""
  tls: "false"
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
